<a href="https://colab.research.google.com/github/shelepadaniella/big-query-customer-analysis/blob/main/Lecture_24_%D0%A8%D0%B5%D0%BB%D0%B5%D0%BF%D0%B0_%D0%94%D0%B0%D0%BD%D1%96%D0%B5%D0%BB%D0%BB%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.cloud import bigquery
from google.oauth2 import service_account
import pandas as pd

credentials = service_account.Credentials.from_service_account_file('/content/firm-reef-477813-j3-624c611e54be.json')

project_id = 'firm-reef-477813-j3'
client = bigquery.Client(credentials=credentials,project=project_id)


query_text = f'''select current_timestamp as ts'''

query = client.query(query_text)

result_df = query.to_dataframe()
result_df.head()

                                ts
0 2026-03-13 15:12:28.423901+00:00

In [ ]:
from google.colab import auth
import google.auth
from google.cloud import bigquery
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
project_id = 'firm-reef-477813-j3'
bigquery_client = bigquery.Client(project = project_id)


dataset_id = 'junior_da_py_personal'
table_id = 'customers_data'

query = (
    'SELECT * '
    'FROM `firm-reef-477813-j3.junior_da_py_personal.d_customers` '
)

query_job = bigquery_client.query(query)

customers_data = query_job.result().to_dataframe()
customers_data.head()

  customer_id gender   age
0     C302221   Male  '18'
1     C301349   Male  '18'
2     C570435   Male  '18'
3     C400520   Male  '18'
4     C127047   Male  '18'

In [ ]:
from google.colab import auth
import google.auth
from google.cloud import bigquery
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
project_id = 'firm-reef-477813-j3'
bigquery_client = bigquery.Client(project = project_id)


dataset_id = 'junior_da_py_personal'
table_id = 'shopping_data'

query = (
    'SELECT * '
    'FROM `firm-reef-477813-j3.junior_da_py_personal.d_shopping_data` '
)

query_job = bigquery_client.query(query)

shopping_data = query_job.result().to_dataframe()
shopping_data.head()

,invoice_no,customer_id,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I318200,C203784,Technology,1,1050,Debit Card,2021-11-24,Kanyon
1,I302497,C460321,Technology,1,1050,Cash,2022-09-25,Kanyon
2,I170954,C102097,Technology,1,1050,Cash,2021-04-27,Kanyon
3,I610881,C491361,Technology,1,1050,Cash,2022-08-01,Kanyon
4,I251842,C960918,Technology,1,1050,Cash,2022-03-11,Kanyon

In [ ]:
customers_data = customers_data.drop_duplicates()

In [ ]:
shopping_data = shopping_data.drop_duplicates()

In [ ]:
import pandas as pd
unioned_stat = pd.merge(shopping_data, customers_data, how='left', on="customer_id")
# unioned_stat['price'] = unioned_stat['price'].astype(float)
unioned_stat['price'] = unioned_stat['price'].replace(',', '.', regex=True).astype(float)
unioned_stat['category'].fillna("UNKNOWN", inplace=True)
filtered_stat = unioned_stat.dropna(subset=["shopping_mall"])
unioned_stat['invoice_date'] = pd.to_datetime(unioned_stat['invoice_date'])

unioned_stat

/tmp/ipykernel_1499/3304948805.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  unioned_stat['category'].fillna("UNKNOWN", inplace=True)

,invoice_no,customer_id,category,quantity,price,payment_method,invoice_date,shopping_mall,gender,age
0,I318200,C203784,Technology,1,1050.00,Debit Card,2021-11-24,Kanyon,Male,'65'
1,I302497,C460321,Technology,1,1050.00,Cash,2022-09-25,Kanyon,Female,'18'
2,I170954,C102097,Technology,1,1050.00,Cash,2021-04-27,Kanyon,Male,'65'
3,I610881,C491361,Technology,1,1050.00,Cash,2022-08-01,Kanyon,Female,'24'
4,I251842,C960918,Technology,1,1050.00,Cash,2022-03-11,Kanyon,Male,'52'
...,...,...,...,...,...,...,...,...,...,...
102067,I337308,C276839,Clothing,4,1200.32,Cash,2021-10-30,Emaar Square Mall,Male,'28'
102068,I278852,C299694,Clothing,4,1200.32,Cash,2021-06-06,Emaar Square Mall,Female,'23'
102069,I214678,C766797,Clothing,4,1200.32,Cash,2022-01-23,Emaar Square Mall,Male,'60'
102070,I602409,C328416,Shoes,2,1200.34,Credit Card,2022-12-19,Emaar Square Mall,Male,'61'
102071,I860514,C132036,Shoes,5,3000.85,Cash,2022-07-14,Emaar Square Mall,Female,'36'

In [ ]:
unioned_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102072 entries, 0 to 102071
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   invoice_no      102072 non-null  object
 1   customer_id     102072 non-null  object
 2   category        102072 non-null  object
 3   quantity        102072 non-null  object
 4   price           102072 non-null  float64
 5   payment_method  102072 non-null  object
 6   invoice_date    102072 non-null  datetime64[ns]
 7   shopping_mall   102040 non-null  object
 8   gender          102072 non-null  object
 9   age             102072 non-null  object
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 7.8+ MB